palkan/action_policy

.gitignore
.travis.yml
lib/action_policy/ext/module_namespace.rb
lib/action_policy/ext/string_match.rb
test/action_policy/rails/controllers_helper.rb
test/action_policy/rails/controllers_test.rb
test/action_policy/rails/views_test.rb

Fix Ruby 2.3 compatibility

---

docs/lookup_chain.md
docs/rails.md

Just a few fixes to the documentation; things that tripped me up along the way :)

Documentation fix

---

CHANGELOG.md
lib/action_policy/behaviour.rb

Use send() instead of public_send() when retrieving authorization_context

---

CHANGELOG.md
docs/lookup_chain.md
lib/action_policy/lookup_chain.rb
test/action_policy/lookup_chain_test.rb

Addresses #45. I've used the code from the [comment](https://github.com/palkan/action_policy/issues/17#issuecomment-398693964) with the minor changes related to the namespace handling.
PR checklist:

Add Symbol lookup to the default lookup chain

---

LICENSE.txt

Update copyright notice to 2019

---

docs/aliases.md
docs/authorization_context.md

fix minor typos in doc

---

docs/quick_start.md

Fixes #59 , at least partially (improves the situation :) ).

fix examplary Post{s,}Controller, mention singularity

---

docs/writing_policies.md

Just put a link in the doc where it seems appropriate.

doc: link authorize! and allowed_to? doc

---

CHANGELOG.md
docs/authorization_context.md
lib/action_policy/behaviours/policy_for.rb
test/action_policy/behaviour_test.rb

Add explicit context option

---

docs/custom_policy.md

ActionPolicy::Base includes Scoping module

---

docs/testing.md

Update the testing documentation.
I added section about `Testing params scopes` and `Testing views`.
I not sure about the section `Testing views`.
PR checklist:
Closes #88, #105

Improve testing documentation

---

lib/generators/action_policy/install/templates/application_policy.rb

Fix typo at application_policy.rb's comment.

---

CHANGELOG.md
docs/lookup_chain.md
lib/action_policy/lookup_chain.rb
test/action_policy/lookup_chain_test.rb

Attempt to fix the namespace lookup issue mentioned on #123.

fix(lookup): add strict option for namespace lookups

---

lib/action_policy/policy/reasons.rb
test/action_policy/policy/aliases_test.rb

Fix aliases in policies with reasons

---

docs/testing.md

PR checklist:
- [-] Tests included
- [-] Changelog entry added

Fix copypasta

---

docs/graphql.md

Minor documentation update to inform users that they need to add error handling to their schema.
For reference : https://graphql-ruby.org/errors/error_handling.html#setup
PR checklist:

Update the graphql documentation exception part

---

docs/rails.md

Minor documentation update

---

docs/rails.md

docs: minor grammar improvements

---

docs/testing.md

https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md012---multiple-consecutive-blank-lines
PR checklist:

Removed multiple consecutive blank lines

---

.github/workflows/docs-lint.yml
.github/workflows/rubocop.yml
.github/workflows/test-jruby.yml
.github/workflows/test.yml

Update checkout action version to v4.

---

Gemfile
docs/debugging.md
forspell.dict
gemfiles/rails6.gemfile
gemfiles/rails7.gemfile
gemfiles/rails71.gemfile
lib/action_policy/policy/core.rb
lib/action_policy/utils/pretty_print.rb

Hi @palkan. Please check my PR by issue https://github.com/palkan/action_policy/issues/262

Migrate pretty print to Prism #262

---

CHANGELOG.md
lib/action_policy/authorizer.rb
test/action_policy/behaviour_test.rb
test/action_policy/rails/controllers_test.rb

Improve Not Authorized exception message

---

docs/rails.md

Fixed typo in readme
