- CHANGELOG.md
- lib/action_policy/base.rb
Fix the modules order in `ActionPolicy::Base`.
When we apply the rule, we are calling all `apply` methods from the modules. If the user sets `pre_check` in `ApplicationPolicy` and this method returns `deny!`, `ApplicationPolicy` raises an exception:
```ruby
NoMethodError (undefined method `add' for nil:NilClass)
```
Code example:
```
class ApplicationPolicy < ActionPolicy::Base
pre_check :allowed_for_user
private
def allowed_for_user
deny!
end
end
```
The main reason for this error is that `reasons` in policy is nil:
https://github.com/palkan/action_policy/blob/becc4f9238458696ae9f406e38e3c903e5765655/lib/action_policy/policy/pre_check.rb#L86
This is because the `PreCheck#apply` method calls **before** `Reasons#apply` and `reasons` is not initialized.
My fix changes modules order and the …
> Change the base modules order

- README.md
Just a typo fix/minor documentation update.
Thanks for your work on this gem!
> Fix link to the documentation

- CHANGELOG.md
- lib/action_policy/cache_middleware.rb
- lib/action_policy/middleware.rb
- lib/action_policy/railtie.rb
Fixes #19
Fixes the initialisation of `action_policy` on Rails < 5 by moving the cache clearing into a Rack Middleware wrapping the request cycle.
Added a code branch based on the rails version and replicated the thread clearing 'callbacks' in a Middleware that will be used if one is using Rails < 5.
I added no tests because you mentioned there were no tests on the railtie anyway. Feel free to add some but I'm not sure where to start. Perhaps an integration test to make sure caching works as expected and is cleared per-request?
-->
PR checklist:
> Fix initialisation for Rails < 5

- docs/_sidebar.md
- docs/controller_action_aliases.md
- docs/index.html
Add Tips & Tricks section
Fix scroll to top issue with sidebar links
> Add Controller Action Aliases proposal to README

- CHANGELOG.md
- docs/aliases.md
- docs/quick_start.md
- lib/action_policy/policy/aliases.rb
- test/action_policy/policy/aliases_test.rb
Fixes #18
The rule lookup process with respect to aliases was flawed as it gave precedence to existing methods in ancestors before looking up aliases. This meant that one couldn't override an existing method on an ancestor with an alias to another method in the subclass.
Modified the rule lookup process:
1. Look only at the methods of this class for the rule first.
2. If not found, look at the rules_aliases for a match, return matched alias target if found.
3. If not found, look at superclass (and ancestors) methods for a match.
4. If not found, look for the default rule.
5. If not found, call super to raise an error.
Coding style and perhaps oversights in logic.
PR checklist:
> Fix alias lookup

- docs/namespaces.md
Make this configuration documentation consistent with other config docs. Though, for clarity it might be better to show the full code:
```ruby
Rails.application.config.action_policy.namespace_cache_enabled
```
> Fix configuration typo

- docs/non_rails.md
I discovered this gem and was reading the documentation when I found this broken link, so here's a PR to fix it
> Fix broken authorization_context link in non_rails.md

- docs/testing.md
- lib/action_policy.rb
- lib/action_policy/authorizer.rb
- lib/action_policy/behaviour.rb
- lib/action_policy/policy/scoping.rb
- lib/action_policy/rspec.rb
- lib/action_policy/rspec/have_authorized_scope.rb
- lib/action_policy/test_helper.rb
- lib/action_policy/testing.rb
- spec/action_policy/rspec_spec.rb
- test/action_policy/policy/scoping_test.rb
- test/action_policy/test_helper_test.rb
Follow-up for #33.
Added testing support to scopes.
Example:
```ruby
class UsersController < ApplicationController
def index
@user = authorized(User.all)
end
end
describe UsersController do
subject { get :index }
it "has authorized scope" do
expect { subject }.to have_authorized_scope(:active_record_relation)
.with(PostPolicy)
end
end
```
> Add scoping testing

- CHANGELOG.md
This was a typo made in 1d4a2e720c0da469d89240abdbd1c44a2daafb1b. There was a PR to correct this in `docs/namespaces.md` (https://github.com/palkan/action_policy/pull/38) but the typo remained in the `CHANGELOG`.
> Remove duplicated `config.` from CHANGELOG entry

- CHANGELOG.md
- docs/scoping.md
- docs/testing.md
- lib/action_policy/behaviour.rb
- lib/action_policy/policy/scoping.rb
- lib/action_policy/rspec/have_authorized_scope.rb
- lib/action_policy/test_helper.rb
- lib/action_policy/testing.rb
- spec/action_policy/rspec_spec.rb
- test/action_policy/behaviour_test.rb
- test/action_policy/policy/scoping_test.rb
- test/action_policy/test_helper_test.rb
- test/stubs/user.rb
Hi! Thank you for a great gem!
Add the ability to add options to Scopes so it can be declared like this: 
```
scope_for :relation do |relation, with_deleted: false, whatever: 42|
...
end
```
And instead of several scopes can be created only one
It can be used this way:
```
authorized blabla, type: :relation, scope_options: { with_deleted: true }
```
`authorized(blabla, type: :relation, with_deleted: true)` would look better, but I don't think we need to mix policy lookup options with scope options
- Added scope_options to `Behaviour#authorized`
- Added scope_options to `Scoping#apply_scope` and made it pass to the policy only when options are present to not break existing scopes which don't expect options
- Updated existing tests to be green
If you like the idea and the syntax, I'll add …
> Ability to add options to scopes

- CHANGELOG.md
- action_policy.gemspec
- docs/i18n.md
- docs/reasons.md
- lib/action_policy.rb
- lib/action_policy/i18n.rb
- test/action_policy/i18n_test.rb
- test/test_helper.rb
I've tried to keep it as similar as much to the [gist](https://gist.github.com/palkan/eb6fab36c5f60e899cccacd3d5649a93) as possible. The major change is that I've added translations of the parent policies to the candidates' list.
I've also added two more Rake tasks for i18n specs, which cover the case when i18n gem is available and also when it's missing (i.e. user tries to use without requiring the gem)
Fixes #15.
> I18n integration

- docs/behaviour.md
- docs/scoping.md
Some minor typos I found while going trough the documentation.
Cheers!
> Fix minor typos in documentation

- CHANGELOG.md
- docs/reasons.md
- docs/testing.md
- lib/action_policy/i18n.rb
- lib/action_policy/policy/core.rb
- lib/action_policy/policy/execution_result.rb
- lib/action_policy/policy/reasons.rb
- lib/action_policy/rspec/dsl.rb
- spec/action_policy/dsl_spec.rb
- test/action_policy/i18n_test.rb
- test/action_policy/policy/reasons_test.rb
Add ability to provide additional information to failure reasons.
Add `details` Hash to specify per-rule meta information:
```ruby
class ApplicantPolicy < ApplicationPolicy
def show?
allowed_to?(:show?, object.stage)
end
end
class StagePolicy < ApplicationPolicy
def show?
details[:title] = record.title
user.stages.where(id: record.id).exists?
end
end
p ex.result.reasons.details #=> { stage: [{show?: {title: "Onboarding"}] }
```
The main purpose of this feature is to generate more descriptive failure messages with i18n.
**No breaking public API changes**.
PR checklist:
> Add detailed reasons

- CHANGELOG.md
- Gemfile
- docs/_sidebar.md
- docs/debugging.md
- docs/testing.md
- gemfiles/rails42.gemfile
- gemfiles/rails6.gemfile
- lib/action_policy/policy/core.rb
- lib/action_policy/rspec/dsl.rb
- lib/action_policy/utils/pretty_print.rb
- spec/action_policy/dsl_spec.rb
- test/action_policy/pp_test.rb
This feature aims to:
- provide better error messages for [RSpec DSL](https://actionpolicy.evilmartians.io/#/testing?id=rspec-dsl)
- provide debug helpers for development.
**NOTE:** this functionality requires two additional gems to be available in the app:
- [unparser](https://github.com/mbj/unparser)
- [method_source](https://github.com/banister/method_source)
We usually describe policy rules using _boolean expressions_ (e.g. `A or (B and C)`, where each of `A`, `B` and `C` is a simple boolean expression or predicate method).
When dealing with complex policies it could be hard to figure out which predicate/check made policy to fail.
The `Policy#pp(rule)` method aims to help debug such situations.
Consider a (synthetic) example:
```ruby
def feed?
(admin? || allowed_to?(:access_feed?)) && …
```
> Add pretty print for policy rules

- CHANGELOG.md
- docs/scoping.md
- lib/action_policy/behaviour.rb
- lib/action_policy/behaviours/policy_for.rb
- lib/action_policy/behaviours/scoping.rb
- lib/action_policy/policy/scoping.rb
- lib/action_policy/test_helper.rb
- spec/action_policy/rspec_spec.rb
- test/action_policy/behaviour_test.rb
- test/action_policy/policy/scoping_test.rb
- test/action_policy/rails/scope_matchers_test.rb
- test/action_policy/test_helper_test.rb
> Improve scoping

- CHANGELOG.md
- docs/instrumentation.md
- lib/action_policy/authorizer.rb
- lib/action_policy/policy/cache.rb
- lib/action_policy/policy/core.rb
- lib/action_policy/policy/execution_result.rb
- lib/action_policy/rails/authorizer.rb
- lib/action_policy/rails/policy/instrumentation.rb
- lib/action_policy/railtie.rb
- test/action_policy/policy/cache_test.rb
- test/action_policy/rails/instrumentation_test.rb
- test/action_policy/rails/policy/instrumentation_test.rb
- test/stubs/in_memory_cache.rb
This PR adds instrumentation support (`ActiveSupport::Notifications`-based).
PR checklist:
> Add instrumentation for Rails apps

- docs/decorators.md
The code was trying to look for `ActionPolicy::Draper::Decorator` instead of looking for `Draper::Decorator` at the top level.
> docs: fix decorators example not working correctly

- docs/graphql.md
- docs/testing.md
This PR fixes some typos in the GraphQl and testing docs
> Fix Typos in GraphQL and Testing Docs

- docs/reasons.md
Policy reasons needed to be nested under the `action_policy` key to translate properly.
> Fix locale file in reasons documentation

- docs/pundit_migration.md
Found a link with an empty href (returns to root page) when looking through the documentation.
> Fix empty link in docs

- lib/action_policy/policy/core.rb
If the inner block raises an error it was possible that `@result` would
not be reset.
> with_clean_result: reset `@result` with ensure

- CHANGELOG.md
- docs/authorization_context.md
- lib/action_policy/policy/authorization.rb
- test/action_policy/policy/authorization_test.rb
As suggested in https://github.com/palkan/action_policy/issues/89#issuecomment-557717110
it allows making authorization context optional
Don't raise `AuthorizationContextMissing` from `ActionPolicy::Policy::Authorization` if authorization target was defined with has `optional: true`
PR checklist:
> Feat: optional authorization context

- lib/action_policy/policy/core.rb
- lib/action_policy/policy/reasons.rb
The code already does this when record is not provided as the code treats that
as executing with the same record. In the case where the record is in fact the same
we should run the same code path.
> allowed_to?: don't lookup policy if record is the same as the current policy

- CHANGELOG.md
- docs/caching.md
- lib/action_policy/ext/policy_cache_key.rb
- lib/action_policy/policy/cache.rb
- test/action_policy/ext/policy_cache_key_test.rb
- test/action_policy/policy/cache_test.rb
- test/action_policy/rails/active_record_helper.rb
- test/action_policy/rails/cache_test.rb
Allows you to cache anything in policy classes using the Action Policy cache key generation mechanism.
> Improve caching

- lib/action_policy/rspec/dsl.rb
Specify titles for tests, so that running rspec with `--format documentation` returns meaningful details like:
```
ProjectPolicy
index?
when not authenticated
is disallowed
when user is reader
is allowed
```
Added titles to rspec `specify`
Titles make sense? Better ideas?
PR checklist:
> titles for specs

- CHANGELOG.md
- benchmarks/catch_throw.rb
- docs/reasons.md
- docs/writing_policies.md
- lib/action_policy/policy/core.rb
- lib/action_policy/policy/pre_check.rb
- lib/action_policy/policy/reasons.rb
- test/action_policy/policy/core_test.rb
- test/action_policy/policy/pre_check_test.rb
- test/action_policy/policy/reasons_test.rb
Make `allow!` and `deny!` available in policy rules.
Closes #120.
PR checklist:
> Move deny!/allow! to core

- CHANGELOG.md
- action_policy.gemspec
- config/rubocop-rspec.yml
- docs/testing.md
Previously, RuboCop RSpec failed to detect RSpec aliases. A number of cops were failing false offences, and some cops were unable to lint, as they were skipping locally defined RSpec aliases taking them for arbitrary blocks and method calls.
See:
- https://github.com/rubocop-hq/rubocop-rspec/issues/1077
- https://github.com/rubocop-hq/rubocop-rspec/pull/956
- https://github.com/palkan/action_policy/issues/103
Example project:
`Gemfile`:
```ruby
source 'https://rubygems.org'
gem 'action_policy', path: '../../action_policy'
gem 'rubocop-rspec'
```
`.rubocop.yml`:
```yaml
AllCops:
NewCops: enable
require:
- rubocop-rspec
inherit_gem:
action_policy: .rubocop-rspec-aliases.yml
```
`spec/policies/a_policy_spec.rb`:
```ruby
RSpec.describe 'A' do
describe_rule :luck? do
succeed 'when stars align' …
```
> Add RuboCop RSpec support

- CHANGELOG.md
- lib/action_policy/lookup_chain.rb
- test/action_policy/lookup_chain_test.rb
Hello,
We recently looked at enabling the strict_namespace option globally to ensure people are adding new policies in a particular namespace. Unfortunately we couldn't because it'd break the lookup in other areas. Here's the commit description:
---
Previously, we'd skip some lookups when `namespace` was nil and others when `strict` was true. This resulted in a situation where you'd not find a non-namespaced `ThingPolicy` when using the lookup with `strict_namespace: true`.
With the changes of this commit, the lookup will start finding `ThingPolicy` in strict mode if and only if the authorisation namespace is nil.
---
I _think_ the previous behaviour was buggy and not documented so I wouldn't consider it to be a breaking change. The change also allows us to simplify the lookup code a …
> Fix global policies not being found with `strict_namespace: true`

- CHANGELOG.md
- docs/aliases.md
- lib/action_policy.rb
- lib/action_policy/policy/aliases.rb
- lib/action_policy/policy/core.rb
- test/action_policy/policy/enforce_predicate_rules_naming_test.rb
to catch the rule missing question mark. 
Fixes #139
PR checklist:
- [x ] Tests included
- [ x] Documentation updated
- [ x] Changelog entry added
> Add `ActionPolicy.enforce_predicate_rules_naming` config 

- CHANGELOG.md
- lib/action_policy/behaviour.rb
When comparing a `record` to a special symbol, it's safer to do `:__undef__ == record` than to do `record == :__undef__`. This is because `Symbol#==` is more reliable than the polymorphic `#==` method on `record`, which could do anything.
One example of this is [`ActiveRecord::AssociationRelation#==`](https://github.com/rails/rails/blob/070d4afacd3e9721b7e3a4634e4d026b5fa2c32c/activerecord/lib/active_record/association_relation.rb#L14), which has the unwanted side effect of executing a database query if it is passed in to ActionPolicy as the `record` argument.
Fixes #179
PR checklist:
> Prevent possible side effects in policy lookup

- CHANGELOG.md
- docs/reasons.md
- lefthook.yml
- lib/action_policy/policy/core.rb
- lib/action_policy/policy/reasons.rb
- test/action_policy/policy/reasons_test.rb
Closes #186 
Added `allowed_to?(:rule, obj, inline_reasons: true)` to merge reasons into the current reasons set.
PR checklist:
> Add inline_reasons option to allowed_to?

- docs/testing.md
- lib/action_policy/rspec.rb
- lib/action_policy/rspec/be_an_alias_of.rb
- spec/action_policy/rspec_spec.rb
Adds `#be_an_alias_of` RSpec matcher as proposed in #189
I've added the `#be_an_alias_of` matcher, tests, and documentation for it. It works like this:
```ruby
describe '#show?' do
it 'is an alias to #index? rule' do
expect(:show?).to be_an_alias_of(policy, :index?)
end
end
```
The changelog mentions only changes made within versions, and a future release will include this change. Therefore I did not add anything to the changelog. Not sure that it's OK.
I forbid block matches for this RSpec matcher - not sure if this is expected behavior.
Also, we could add some kind of helper for our `dsl`, but it might be confusing for developers, so maybe we should just add a matcher. I think adding alias matcher to `dsl` might have negative consequences for the clarity of action policy tests written …
> [189] | Add #be_an_alias_of rspec matcher

- CHANGELOG.md
- lib/action_policy/ext/module_namespace.rb
fixes #207 refinement#include deprecation warning
PR checklist:
> Fix for refinement#include deprecation warning

- docs/authorization_context.md
Fairly certain the documentation has a typo where `subsets` is used, but `supersets` is intended.
> ✏️ superset != subset

- docs/testing.md
When running the code sample as is, I get this error:
```
Failure/Error: before { user.update!(role: :user) }
RuntimeError:
stubbed models are not allowed to access the database - User#update!({:role=>:user})
```
So instead of updating the stubbed user, I just change the attribute value.
> Fix testing docs (stubbed models cannot access DB)

- docs/scoping.md
I can't find any other occurrence of `my_data` in the repository, whereas the specs use `scope_for :data` (for instance [here](https://github.com/palkan/action_policy/blob/d8c76db9a220138dfbf4b809c17b063e157081a9/test/action_policy/policy/scoping_test.rb#L13)).
I guess it's a good idea to make it consistent.
PR checklist:
> Docs: rename my_data > data

- lib/generators/rspec/templates/policy_spec.rb.tt
`File.exists?` has been deprecated and removed in Ruby 3.2. As a result, rails generator fails:
```
/Users/u/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/action_policy-0.6.4/lib/generators/rspec/templates/policy_spec.rb.tt:1:in `template': undefined method `exists?' for File:Class (NoMethodError)
@output_buffer = ''.dup; @output_buffer.concat "require \"".freeze; @output_buffer.concat(( File.exists?('spec/rails_helper.rb') ? 'rails_helper' : 'spec_helper' ).to_s); @output_buffer.concat "\"\n\nRSpec.describe ".freeze
^^^^^^^^
Did you mean?  exist?
```
https://bugs.ruby-lang.org/issues/17391
> Replace File.exists?

- docs/aliases.md
We searched a while to figure out why spelling mistakes caused an `Unauthorized` error instead of an `UnknownRule` error.
It took us very long to realize that the `default_rule` has a default value of `manage?`, and that this rule by default also returns `false`. 
This change improves the documentation somewhat IMO.
Though I wonder if the `default_rule` needs a default value at all. Both actions and rules are usually not dynamic. So any mismatch is a code issue and not an authorization issue. Thus I think that raising an `UnknownRule` makes more sense and it makes debugging easier. 
For anyone who does want a fallback to `manage?`, when following the usage guide in the readme, it's only a single line of code. But at least it's a conscious decision that way.
PR checklist:
> Improving the alias documentation

- CHANGELOG.md
- README.md
- docs/rails.md
- lib/generators/action_policy/policy/USAGE
- lib/generators/action_policy/policy/policy_generator.rb
- lib/generators/action_policy/policy/templates/policy.rb.tt
- spec/generators/policy_generator_spec.rb
Implements #239
This commit intends to allow using the `--parent` option on the policy generator to specify the parent class of the generated policy.
You can use `--parent=base_policy` or `--parent=BasePolicy` as we call `classify` on the given value for the parent option.
Example:
`bin/rails g action_policy:policy user --parent=base_policy` generates:
```ruby
class UserPolicy < BasePolicy
...
end
```
PR checklist:
> feat: Add --parent to policy generator to specify parent class of Policy

- README.md
Hi, this is just a small PR to include our [integration](https://github.com/shrimple-tech/action_policy-graphiti) of Action Policy with JSON:API implementation ([Graphiti](https://github.com/graphiti-api/graphiti)) into the readme.
> Add Graphiti integration to the readme

- docs/testing.md
- lib/action_policy/rspec/have_authorized_scope.rb
- lib/action_policy/test_helper.rb
- lib/action_policy/testing.rb
- spec/action_policy/rspec_spec.rb
- test/action_policy/test_helper_test.rb
Hi @palkan. I added `with_context` qualifier to `have_authorized_scope` matcher
Discussed in https://github.com/palkan/action_policy/issues/258
PR checklist:
> Added `with_context` qualifier to `have_authorized_scope` matcher

- docs/scoping.md
- lib/action_policy/policy/scoping.rb
- test/action_policy/rails/scope_matchers_test.rb
Hi @palkan. Please check my PR by issue #261
> Allow using callable objects as scopes #261

- docs/reasons.md
Enhance example about output of `all_details` in documentation to better understand what we should expect.
Linked to #278
> Enhance example for `all_details`  to disambiguates expected output

- CHANGELOG.md
- lib/action_policy/rails/controller.rb
- test/action_policy/rails/views/users/index.html.erb
- test/action_policy/rails/views_test.rb
Enable the allowance_to method as a default helper method.
We use `allowance_to` to display disabled buttons with helpful messages, like "You don't have edit permission" or "Cannot edit archived documents". While adding `helper_method :allowance_to` to `ApplicationController` works, it breaks component/view tests because `ActionView::TestCase::TestController` (which includes `ActionPolicy::Controller`) doesn't expose this helper.
To fix this, we had to manually reopen the TestController class:
```ruby
class ActionView::TestCase::TestController
helper_method :allowance_to
end
```
It would be helpful if `allowance_to` was a default helper to simplify usage and avoid such issues.
On `ActionPolicy::Controller` I added `helper_method :allowance_to` along with `allowed_to?` and …
> Enable 'allowance_to' as helper method by default

- CHANGELOG.md
- lib/action_policy/behaviour.rb
- lib/action_policy/rails/controller.rb
- test/action_policy/rails/controllers_test.rb
Fixes #286. NB: I am new to this framework, so please double-check.
PR checklist:
Tested with `bundle exec rake test && bundle exec rspec`.
> let authorize! return the policy record

- CHANGELOG.md
- docs/authorization_context.md
- docs/rails.md
- lib/action_policy/behaviour.rb
- test/action_policy/rails/controllers_test.rb
Closes #291
Allows one to provide a proc to `authorize`'s `:through` option.
Extended `build_authorization_context` to cope with a proc being passed in.
No.
PR checklist:
> Allow the `:through` option of `authorize` to be passed a proc
